---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
  namespace: test-nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - mountPath: /var/cache/nginx
          name: nginx-cache
        securityContext:
          runAsUser: 101  # Default Nginx user
          runAsGroup: 101
        ports:
        - containerPort: 80
      volumes:
      - name: nginx-cache
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  namespace: test-nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
